### ISSUE TITLE
1.18.2 compability

### ISSUE THREAD

**Issue by sphings79** [fantahund/LobbySecrets#2]
> version
[15:21:38 INFO]: This server is running Paper version git-Paper-220 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 63aa4d3)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)
> version secrets
[15:21:41 INFO]: Secrets version 1.4.1
[15:21:41 INFO]: Author: fanta & Shanawi
>

```
[15:12:08 WARN]: [Secrets] Task #5527 for Secrets v1.4.1 generated an exception
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at de.tr7zw.nbtapi.utils.ApiMetricsLite.submitData(ApiMetricsLite.java:296) ~[item-nbt-api-plugin-2.9.1.jar:?]
        at de.tr7zw.nbtapi.utils.ApiMetricsLite.access$100(ApiMetricsLite.java:35) ~[item-nbt-api-plugin-2.9.1.jar:?]
        at de.tr7zw.nbtapi.utils.ApiMetricsLite$1.lambda$run$0(ApiMetricsLite.java:179) ~[item-nbt-api-plugin-2.9.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1521) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by fantahund** [comment]
When exactly does the error occur? Everything works without problems for me.

**Comment by fantahund** [comment]
I just see an error in the stacktrace of the Item-NBT-API have you already brought this up to date?
https://ci.codemc.io/job/Tr7zw/job/Item-NBT-API/

**Comment by fantahund** [comment]
I just tested it. You have to update the NBT API after that everything should work again.

**Comment by sphings79** [comment]
Yes you are right. Thx
